name: commit ci
on: [push]
env:
  CI_NAME: Commit CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout last commit
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
          # will restore cache of dependencies and wrappers
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

#      - name: Soptless code style check
#        run: ./gradlew spotlessCheck

      - name: Spotless code style check
        run: make spotless

      - name: Build Trime
        run: make debug

      - name: Upload Trime artifact
        uses: actions/upload-artifact@v3
        with:
          name: trime
          path: app/build/outputs/apk/**/*.apk
          # keep 90 days
          retention-days: 90

      - name: Upload Trime artifact (ARM64_V8A only)
        uses: actions/upload-artifact@v3
        with:
          name: trime_arm64_v8a
          path: app/build/outputs/apk/**/*arm64-v8a-debug.apk
          # keep 90 days
          retention-days: 90

      - name: Upload jni artifact (librime_jni.so)
        uses: actions/upload-artifact@v3
        with:
          name: librime_jni
          path: app/build/intermediates/stripped_native_libs/debug/out/lib/*
          # keep 90 days
          retention-days: 90
